const API_RESULTS = {
    ERR_LOGIN_ERROR: { descripiton: "Błąd logowania", code: 'ERR_LOGIN_ERROR', status_code: 500 },
    ERR_REGISTER_ERROR: { descripiton: "Błąd rejestracji", code: 'ERR_REGISTER_ERROR', status_code: 500 },
    ERR_REFRESH_TOKEN: { descripiton: "Błąd odświeżania tokena", code: 'ERR_REFRESH_TOKEN', status_code: 500 },
    ERR_VERIFY_TOKEN: { descripiton: "Błąd weryfikacji tokenu", code: 'ERR_VERIFY_TOKEN', status_code: 500 },
    ERR_READ_FILE: { descripiton: "Błąd odczytu pliku", code: 'ERR_READ_FILE', status_code: 500 },
    ERR_GET_ROLES: { descripiton: "Wystąpił błąd podczas pobierania ról", code: 'ERR_GET_ROLES', status_code: 500 },
    ERR_CREATE_ROLE: { descripiton: "Wystąpił błąd podczas dodawania roli", code: 'ERR_CREATE_ROLE', status_code: 500 },
    ERR_EDIT_ROLE: { descripiton: "Wystąpił błąd podczas aktualizacji roli", code: 'ERR_EDIT_ROLE', status_code: 500 },
    ERR_DELETE_ROLE: { descripiton: "Wystąpił błąd podczas usuwania roli", code: 'ERR_DELETE_ROLE', status_code: 500 },
    ERR_GET_USERS: { descripiton: "Wystąpił błąd podczas pobierania użytkowników", code: 'ERR_GET_USERS', status_code: 500 },
    ERR_GET_MESSAGES: { description: "Wystąpił błąd podczas pobierania wiadomości", code: 'ERR_GET_MESSAGES', status_code: 500 },
    ERR_LOGOUT_ERROR: { description: "Wystąpił problem z wylogowaniem", code: 'ERR_LOGOUT_ERROR', status_code: 500 },
    ERR_SEND_EMAIL: { description: 'Wystąpił problem z wysyłką wiadomości email', code: 'ERR_SEND_EMAIL', status_code: 500 },
    ERR_ACTIVATE_ACCOUNT_ERROR: { description: 'Wystąpił problem z aktywacją konta', code: 'ERR_ACTIVATE_ACCOUNT_ERROR', status_code: 500 },
    ERR_SOMETHING_WENT_WRONG: { description: 'Coś poszło nie tak', code: 'ERR_SOMETHING_WENT_WRONG', status_code: 500 },
    
    ERR_PROVIDE_LOGIN_DATA: { descripiton: "Musisz wprowadzić dane logowania", code: 'ERR_PROVIDE_LOGIN_DATA', status_code: 400 },
    ERR_PROVIDE_EMAIL_FIELD: { descripiton: "Musisz wypełnić pole \"email\"", code: 'ERR_PROVIDE_EMAIL_FIELD', status_code: 400 },
    ERR_PROVIDE_PASSWORD_FIELD: { descripiton: "Musisz wypełnić pole \"password\"", code: 'ERR_PROVIDE_PASSWORD_FIELD', status_code: 400 },
    ERR_WRONG_PASSWORD: { descripiton: "Niepoprawne hasło", code: 'ERR_WRONG_PASSWORD', status_code: 401 },
    ERR_PROVIDE_DEVICE_TOKEN: { descripiton: "Musisz przekazać Device-Token w nagłówku", code: 'ERR_PROVIDE_DEVICE_TOKEN', status_code: 400 },
    ERR_PROVIDE_LOGIN_TOKEN: { descripiton: "Musisz przekazać Token w nagłówku", code: 'ERR_PROVIDE_LOGIN_TOKEN', status_code: 400 },
    ERR_PROVIDE_REFRESH_TOKEN: { descripiton: "Musisz przekazać Refresh-Token w nagłówku", code: 'ERR_PROVIDE_REFRESH_TOKEN', status_code: 400 },
    ERR_REFRESH_TOKEN_EXPIRED: { descripiton: "Refresh-Token jest nieaktualny", code: 'ERR_REFRESH_TOKEN_EXPIRED', status_code: 401 },
    ERR_TOKEN_EXPIRED: { descripiton: "Token jest nieaktualny", code: 'ERR_TOKEN_EXPIRED', status_code: 401 },
    ERR_WRONG_DEVICE_TOKEN: { descripiton: "Device-Token jest niepoprawny", code: 'ERR_WRONG_DEVICE_TOKEN', status_code: 401 },
    ERR_USER_FROM_TOKEN_NOT_EXISTS: { descripiton: "Użytkownik z tokena nie istnieje", code: 'ERR_USER_FROM_TOKEN_NOT_EXISTS', status_code: 404 },
    ERR_USER_NOT_EXISTS: { descripiton: "Użytkownik nie istnieje", code: 'ERR_USER_NOT_EXISTS', status_code: 404 },
    ERR_USER_ALREADY_EXISTS: { descripiton: "Użytkownik z takim mailem już istnieje", code: 'ERR_USER_ALREADY_EXISTS', status_code: 400 },
    ERR_ROLE_NAME_IS_RESERVED: { descripiton: "Nie możesz dodać roli o tej nazwie", code: 'ERR_ROLE_NAME_IS_RESERVED', status_code: 403 },
    ERR_ROLE_ALREADY_EXISTS: { descripiton: "Taka rola już istnieje", code: 'ERR_ROLE_ALREADY_EXISTS', status_code: 400 },
    ERR_PROVIDE_NAME_FIELD: { descripiton: "Musisz przekazać wartość pola \"name\"", code: 'ERR_PROVIDE_NAME_FIELD', status_code: 400 },
    ERR_ROLE_NOT_EXISTS: { descripiton: "Rola nie znaleziona", code: 'ERR_ROLE_NOT_EXISTS', status_code: 404 },
    ERR_ROLE_EDIT_NAME_IS_RESERVED: { descripiton: "Nie możesz edytować tej roli, jest ona zablokowana", code: 'ERR_ROLE_EDIT_NAME_IS_RESERVED', status_code: 403 },
    ERR_ROLE_EDIT_ALREADY_EXISTS: { descripiton: "Nie możesz zmienić nazwy roli na taką, taka już istnieje", code: 'ERR_ROLE_EDIT_ALREADY_EXISTS', status_code: 400 },
    ERR_ROLE_DELETE_NAME_IS_RESERVED: { descripiton: "Nie możesz usunąć tej roli, jest ona zablokowana", code: 'ERR_ROLE_DELETE_NAME_IS_RESERVED', status_code: 403 },
    ERR_ADMIN_PRIVILEGES_REQUIRED: { descripiton: "Ta czynność wymaga uprawnień admina", code: 'ERR_ADMIN_PRIVILEGES_REQUIRED', status_code: 403 },
    ERR_WRONG_AUTH_PIN: { description: 'PIN aktywacyjny jest niepoprawny', code: 'ERR_WRONG_AUTH_PIN', status_code: 400 },
    ERR_USER_IS_ALREADY_ACTIVATED: { description: 'Użytkownik jest już aktywowany', code: 'ERR_USER_IS_ALREADY_ACTIVATED', status_code: 400 },
    ERR_USER_IS_NOT_ACTIVATED: { description: 'Użytkownik jeszcze nie został aktywowany. Musisz potwierdzić maila', code: 'ERR_USER_IS_NOT_ACTIVATED', status_code: 400 },
    ERR_INVALID_EMAIL_ADDRESS: { description: 'Adres email jest niepoprawny', code: 'ERR_INVALID_EMAIL_ADDRESS', status_code: 400 },

    SUCCESS_CREATED_ROLE: { descripiton: "Pomyślnie utworzono nową rolę", code: 'SUCCESS_CREATED_ROLE', status_code: 201 },
    SUCCESS_EDIT_ROLE: { descripiton: "Pomyślnie zaktualizowano rolę", code: 'SUCCESS_EDIT_ROLE', status_code: 200 },
    SUCCESS_DELETE_ROLE: { descripiton: "Pomyślnie usunięto rolę", code: 'SUCCESS_DELETE_ROLE', status_code: 200 },
    SUCCESS_USER_REGISTERED: { descripiton: "Rejestracja przebiegła pomyślnie", code: 'SUCCESS_USER_REGISTERED', status_code: 201 },
    SUCCESS_LOGOUT: { description: "Wylogowano pomyślnie", code: 'SUCCESS_LOGOUT', status_code: 200 }
}

module.exports = API_RESULTS