const API_RESULTS = {
    ERR_LOGIN_ERROR: { description: "Błąd logowania", code: 'ERR_LOGIN_ERROR', status_code: 500 },
    ERR_REGISTER_ERROR: { description: "Błąd rejestracji", code: 'ERR_REGISTER_ERROR', status_code: 500 },
    ERR_REFRESH_TOKEN: { description: "Błąd odświeżania tokena", code: 'ERR_REFRESH_TOKEN', status_code: 500 },
    ERR_VERIFY_TOKEN: { description: "Błąd weryfikacji tokenu", code: 'ERR_VERIFY_TOKEN', status_code: 401 },
    ERR_READ_FILE: { description: "Błąd odczytu pliku", code: 'ERR_READ_FILE', status_code: 500 },
    ERR_GET_ROLES: { description: "Wystąpił błąd podczas pobierania ról", code: 'ERR_GET_ROLES', status_code: 500 },
    ERR_CREATE_ROLE: { description: "Wystąpił błąd podczas dodawania roli", code: 'ERR_CREATE_ROLE', status_code: 500 },
    ERR_EDIT_ROLE: { description: "Wystąpił błąd podczas aktualizacji roli", code: 'ERR_EDIT_ROLE', status_code: 500 },
    ERR_DELETE_ROLE: { description: "Wystąpił błąd podczas usuwania roli", code: 'ERR_DELETE_ROLE', status_code: 500 },
    ERR_GET_USERS: { description: "Wystąpił błąd podczas pobierania użytkowników", code: 'ERR_GET_USERS', status_code: 500 },
    ERR_GET_MESSAGES: { description: "Wystąpił błąd podczas pobierania wiadomości", code: 'ERR_GET_MESSAGES', status_code: 500 },
    ERR_LOGOUT_ERROR: { description: "Wystąpił problem z wylogowaniem", code: 'ERR_LOGOUT_ERROR', status_code: 500 },
    ERR_SEND_EMAIL: { description: 'Wystąpił problem z wysyłką wiadomości email', code: 'ERR_SEND_EMAIL', status_code: 503 },
    ERR_ACTIVATE_ACCOUNT_ERROR: { description: 'Wystąpił problem z aktywacją konta', code: 'ERR_ACTIVATE_ACCOUNT_ERROR', status_code: 500 },
    ERR_SOMETHING_WENT_WRONG: { description: 'Coś poszło nie tak', code: 'ERR_SOMETHING_WENT_WRONG', status_code: 500 },
    ERR_GET_AUTH_HISTORY: { description: 'Wystąpił problem z pobraniem auth history', code: 'ERR_GET_AUTH_HISTORY', status_code: 500 },
    ERR_GET_APP_CONFIG: { description: 'Wystąpił problem z pobraniem konfiguracji aplikacji', code: 'ERR_GET_APP_CONFIG', status_code: 500 },
    ERR_EDIT_APP_CONFIG: { description: 'Wystąpił problem z edycją konfiguracji aplikacji', code: 'ERR_EDIT_APP_CONFIG', status_code: 500 },
    ERR_INTERNAL_SERVER_ERROR: { description: 'Internal Server Error', code: 'ERR_INTERNAL_SERVER_ERROR', status_code: 500 },
    
    ERR_PROVIDE_LOGIN_DATA: { description: "Musisz wprowadzić dane logowania", code: 'ERR_PROVIDE_LOGIN_DATA', status_code: 400 },
    ERR_PROVIDE_EMAIL_FIELD: { description: "Musisz wypełnić pole \"email\"", code: 'ERR_PROVIDE_EMAIL_FIELD', status_code: 400 },
    ERR_PROVIDE_PASSWORD_FIELD: { description: "Musisz wypełnić pole \"password\"", code: 'ERR_PROVIDE_PASSWORD_FIELD', status_code: 400 },
    ERR_PROVIDE_MESSAGE_FIELD: { description: "Musisz wypełnić pole \"message\"", code: 'ERR_PROVIDE_MESSAGE_FIELD', status_code: 400 },
    ERR_WRONG_PASSWORD: { description: "Niepoprawne hasło", code: 'ERR_WRONG_PASSWORD', status_code: 401 },
    ERR_PROVIDE_DEVICE_TOKEN: { description: "Musisz przekazać Device-Token w nagłówku", code: 'ERR_PROVIDE_DEVICE_TOKEN', status_code: 400 },
    ERR_PROVIDE_LOGIN_TOKEN: { description: "Musisz przekazać Token w nagłówku", code: 'ERR_PROVIDE_LOGIN_TOKEN', status_code: 400 },
    ERR_PROVIDE_REFRESH_TOKEN: { description: "Musisz przekazać Refresh-Token w nagłówku", code: 'ERR_PROVIDE_REFRESH_TOKEN', status_code: 400 },
    ERR_REFRESH_TOKEN_EXPIRED: { description: "Refresh-Token jest nieaktualny", code: 'ERR_REFRESH_TOKEN_EXPIRED', status_code: 401 },
    ERR_TOKEN_EXPIRED: { description: "Token jest nieaktualny", code: 'ERR_TOKEN_EXPIRED', status_code: 401 },
    ERR_WRONG_DEVICE_TOKEN: { description: "Device-Token jest niepoprawny", code: 'ERR_WRONG_DEVICE_TOKEN', status_code: 401 },
    ERR_USER_FROM_TOKEN_NOT_EXISTS: { description: "Użytkownik z tokena nie istnieje", code: 'ERR_USER_FROM_TOKEN_NOT_EXISTS', status_code: 404 },
    ERR_USER_NOT_EXISTS: { description: "Użytkownik nie istnieje", code: 'ERR_USER_NOT_EXISTS', status_code: 404 },
    ERR_USER_ALREADY_EXISTS: { description: "Użytkownik z takim mailem już istnieje", code: 'ERR_USER_ALREADY_EXISTS', status_code: 409 },
    ERR_ROLE_NAME_IS_RESERVED: { description: "Nie możesz dodać roli o tej nazwie", code: 'ERR_ROLE_NAME_IS_RESERVED', status_code: 403 },
    ERR_ROLE_ALREADY_EXISTS: { description: "Taka rola już istnieje", code: 'ERR_ROLE_ALREADY_EXISTS', status_code: 409 },
    ERR_PROVIDE_NAME_FIELD: { description: "Musisz przekazać wartość pola \"name\"", code: 'ERR_PROVIDE_NAME_FIELD', status_code: 400 },
    ERR_ROLE_NOT_EXISTS: { description: "Rola nie znaleziona", code: 'ERR_ROLE_NOT_EXISTS', status_code: 404 },
    ERR_ROLE_EDIT_NAME_IS_RESERVED: { description: "Nie możesz edytować tej roli, jest ona zablokowana", code: 'ERR_ROLE_EDIT_NAME_IS_RESERVED', status_code: 403 },
    ERR_ROLE_EDIT_ALREADY_EXISTS: { description: "Nie możesz zmienić nazwy roli na taką, taka już istnieje", code: 'ERR_ROLE_EDIT_ALREADY_EXISTS', status_code: 409 },
    ERR_ROLE_DELETE_NAME_IS_RESERVED: { description: "Nie możesz usunąć tej roli, jest ona zablokowana", code: 'ERR_ROLE_DELETE_NAME_IS_RESERVED', status_code: 403 },
    ERR_ADMIN_PRIVILEGES_REQUIRED: { description: "Ta czynność wymaga uprawnień admina", code: 'ERR_ADMIN_PRIVILEGES_REQUIRED', status_code: 403 },
    ERR_WRONG_AUTH_PIN: { description: 'PIN aktywacyjny jest niepoprawny', code: 'ERR_WRONG_AUTH_PIN', status_code: 401 },
    ERR_USER_IS_ALREADY_ACTIVATED: { description: 'Użytkownik jest już aktywowany', code: 'ERR_USER_IS_ALREADY_ACTIVATED', status_code: 409 },
    ERR_USER_IS_NOT_ACTIVATED: { description: 'Użytkownik jeszcze nie został aktywowany. Musisz potwierdzić maila', code: 'ERR_USER_IS_NOT_ACTIVATED', status_code: 403 },
    ERR_INVALID_EMAIL_ADDRESS: { description: 'Adres email jest niepoprawny', code: 'ERR_INVALID_EMAIL_ADDRESS', status_code: 422 },
    ERR_REGISTRATION_DISABLED: { description: 'Rejestracja jest wyłączona', code: 'ERR_REGISTRATION_DISABLED', status_code: 423 },
    ERR_LOGIN_DISABLED: { description: 'Logowanie jest wyłączone', code: 'ERR_LOGIN_DISABLED', status_code: 423 },
    ERR_EMAIL_SEND_THROTTLE: { description: 'You have exceeded the limit of requests. Please try again later.', code: 'ERR_EMAIL_SEND_THROTTLE', status_code: 429 },

    ERR_INVALID_FILE_TYPE: { description: 'Invalid file type. Only JPEG, PNG, and GIF are allowed', code: 'ERR_INVALID_FILE_TYPE', status_code: 400 },
    ERR_FILE_SIZE_EXCEEDS_LIMIT: { description: 'File size exceeds the limit of 5 MB', code: 'ERR_FILE_SIZE_EXCEEDS_LIMIT', status_code: 413 },
    ERR_CANNOT_CHANGE_SELF_ROLE: { description: 'Nie można zmienić roli samego siebie', code: 'ERR_CANNOT_CHANGE_SELF_ROLE', status_code: 403 },
    ERR_CANNOT_SEND_MESSAGE_TO_YOURSELF: { description: "Nie możesz wysłać wiadomości do siebie", code: 'ERR_CANNOT_SEND_MESSAGE_TO_YOURSELF', status_code: 403 },
    ERR_CANNOT_CHANGE_SELF_ACTIVATION: { description: 'Nie możesz zmienić sobie statusu aktywacji konta', code: 'ERR_CANNOT_CHANGE_SELF_ACTIVATION', status_code: 403 },

    SUCCESS_CREATED_ROLE: { description: "Pomyślnie utworzono nową rolę", code: 'SUCCESS_CREATED_ROLE', status_code: 201 },
    SUCCESS_EDIT_ROLE: { description: "Pomyślnie zaktualizowano rolę", code: 'SUCCESS_EDIT_ROLE', status_code: 200 },
    SUCCESS_DELETE_ROLE: { description: "Pomyślnie usunięto rolę", code: 'SUCCESS_DELETE_ROLE', status_code: 200 },
    SUCCESS_USER_REGISTERED: { description: "Rejestracja przebiegła pomyślnie", code: 'SUCCESS_USER_REGISTERED', status_code: 201 },
    SUCCESS_LOGOUT: { description: "Wylogowano pomyślnie", code: 'SUCCESS_LOGOUT', status_code: 200 },
    SUCCESS_CHANGE_PASSWORD: { description: "Pomyślnie zmieniono hasło", code: 'SUCCESS_CHANGE_PASSWORD', status_code: 200 },
    SUCCESS_USER_DEACTIVATED: { description: "Pomyślnie dezaktywowano konto", code: 'SUCCESS_USER_DEACTIVATED', status_code: 200 },
    SUCCESS_USER_ACTIVATED: { description: "Pomyślnie aktywowano konto", code: 'SUCCESS_USER_ACTIVATED', status_code: 200 }
}

module.exports = API_RESULTS